apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
