---
- name: Deploy ABC Technologies Project
  hosts: localhost
  vars:
    project_name: "CICD_DOCKER_KUBERNETES"
  become: true
  become_method: sudo
  become_user: jenkins
  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker
        state: present
    - name: Enforcing Deployment File 
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('file','~/.kube/config')}}"
        state: present
        definition: "{{ lookup('file','/home/azureuser/Jenkins_Workspace_New/workspace/{{ project_name }}/processed_deployment.yaml')}}"
    - name: Enforcing Service File 
      kubernetes.core.k8s:
        kubeconfig: "{{ lookup('file','~/.kube/config')}}"
        state: present
        definition: "{{ lookup('file','/home/azureuser/Jenkins_Workspace_New/workspace/{{ project_name }}/processed_service.yaml')}}"




    

